services:
  - docker
os:
  - linux
  - osx

# Build and test
language: rust
rust:
  - stable
  - nightly
  - beta

jobs:
  include:
    # Extra deploy jobs.
    - stage: Deploy
      rust: stable
      os: linux
      env:
        - GITHUB_RELEASE=true
      script: "./build.sh"
    - stage: Deploy
      rust: stable
      os: osx
      env:
        - GITHUB_RELEASE=true
      script: "./build.sh"

    - stage: Deploy
      rust: stable
      script: "echo Deploying to Cargo"
      deploy:
        provider: cargo
        token:
          secure: S77Jo+z1OflPtz+j/0inlW79vVjiRy3oV4rLxwlc/e/oES5EYSqaptcHaizb+gMjhIxOkdPkwtqDe+/Kz3zKqtjtbi73OR47mS7OjUf3loYGjkMEoM3GQRbUB/Qn4y7c4AGxYLrMAK7Pl+6aktDMmKO7SGy+VmuWxNGBm5+tfQ1+dyrl6l/WajZ6fSk1SEef5T2najRu9Jn0m4zlRE2EG+iXDqiPNv7VJNDleIBWQpmnSCFWAhDn0cI+IU0qg17VzGq+nHm7sIFyM4c8TynHzOxghwnkJ+cjn7W3XCCA3vx+aWkUv5lsjqNkxmx27OBfcmAOyDIwABFSg/XdYLWiQJ+//+mmZ0y/ItNy2SxLCUA0smacZT5NOWm/hDh7mYkyGpKp/4LmhekKCRMTIDq5QPQw2zdKTomVQGxSXEHg7ilLIAfv7v/z4MV5HYtWqTN0UL768JDGJbzTjYcoaAIwgWehGWtVb+5nUAcyffVLqaulJ55DTAfzNYvk0otH6LdnEx2Bqs6btgpw2grOIhIJtHBSOJH8Xn15VGOLMw89uQlpqXXvKJ+FBvcIMjJ2KncvI9CMfC620rHga/s0752oL3YoQ/VdNwgKIlYJ575xW1najg0A7eSQ9nhAi+om3todbGuHKIcbsvPtT3CNR47/yBLC6pDuKPVeWSvyntMJZaY=
        on:
          os: linux
          tags: true

  allow_failures:
    - rust: nightly
  fast_finish: true

deploy:
  provider: releases
  api_key:
    secure: V9Nzptxermzw2lCgS88DLMMLnx2vMt50mHG4z1abUiP6mda+rawrL82anyoNlT+HCVwxJM7f2zR0RbyhrM6cJ/8ot4Jts7V3T5lNX6kGBw02Y5n5PfUZJmz/c6g1orjT7g96D7cnaE0wFSimLsll3aOTHb1uveS2tOSm2fcWbvYqz6hoC/nVMCU5cAXZ6+7hfGHxs1PTPRFKnmvUy2ycqx4PIdATo9NNVMxkOBh5MfLd+uAsyuRRzfZhs54FwfSNjDwtCT3Z9eDiPK8m2ncRfLQO/+KmP5mhW+5aeyaZZlgeXk8rct44Wqzu0+l91CRvBlJPN/6oOZzLMOwkyLeXDsnkuR6meONSk+TVTZUbs/3/FDm1UUFuLSX4BSY/txi+Sk2w5Ms+jmx0hAu3fCjDUMaPUHyXj2wAyOietFBUC/Ruo/88Qmcmj5XU9VYUPmZ27nsDkL6bg/sB+f97XcIXOF7etK32twBXjglq31ca3Gr4eNfIF7NJhEaIO55lZRqp6waPCslwXd8dVbtw9Tr2JmSE2FctEZk3rCLkl0FpRppoSfzBJsQB5vaJhiOzxpXCuvqMNxhvjyZlIk5per525nmCXfQs+EbkQZVfmhx9yiXHaAQ4obPSspBemsINr0c5sMNkFugOuyZ+MZjeAgG1fwE1l5mmPodB9jQbtkNtKjM=
  file_glob: true
  file: "floki-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.*"
  skip_cleanup: true
  on:
    tags: true
    condition: "$GITHUB_RELEASE = true"
